apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JiminByun0101/platform-starter-kit
    targetRevision: post-03-gitops-bootstrap 
    path: helm/platform-monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true